DROP TABLE IF EXISTS address, post_office, postal_item, history_item CASCADE;

CREATE TABLE IF NOT EXISTS address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country VARCHAR,
    city VARCHAR,
    house_number VARCHAR,
    CONSTRAINT pk_address PRIMARY KEY(id)
    );


CREATE TABLE IF NOT EXISTS post_office (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    office_index VARCHAR,
    title VARCHAR,
    addres_id BIGINT,
    CONSTRAINT pk_post_office PRIMARY KEY(id),
    CONSTRAINT fk_post_office_to_address FOREIGN KEY(addres_id) REFERENCES address(id),
    CONSTRAINT uq_post_office_office_index UNIQUE (office_index)
    );

CREATE TABLE IF NOT EXISTS postal_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_item VARCHAR(10),
    status VARCHAR(25),
    delivery_address_id BIGINT,
    recipient_name VARCHAR,
    CONSTRAINT pk_postal_item PRIMARY KEY(id),
    CONSTRAINT fk_postal_item_to_post_office FOREIGN KEY(delivery_address_id) REFERENCES post_office(id)
    );

CREATE TABLE IF NOT EXISTS history_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(25),
    created TIMESTAMP,
    post_office_id BIGINT,
    postal_item_id BIGINT,
    CONSTRAINT pk_history_item PRIMARY KEY(id),
    CONSTRAINT fk_history_item_to_post_office FOREIGN KEY(post_office_id) REFERENCES post_office(id),
    CONSTRAINT fk_history_item_to_postal_item FOREIGN KEY(postal_item_id) REFERENCES postal_item(id)
    );